### ISSUE TITLE
如果不同的接口，部署在不一样的站点，客户的调用的时候可以针对每个接口指定不同的域名地址的吗？

### ISSUE THREAD

**Issue by stillwindows7** [xljiulang/WebApiClient#5]
如果不同的接口，部署在不一样的站点，客户的调用的时候可以针对每个接口指定不同的域名地址的吗？

var config = new HttpApiConfig
{
    // 请求的域名，会覆盖[HttpHost]特性
    HttpHost = new Uri("http://www.webapiclient.com"),
};

这个好像是全局配置，有无针对某个接口配置域名地址

**Comment by xljiulang** [comment]
每创建一个HttpApiClient实例都可以传一次域名地址
