### ISSUE TITLE
返回对象是包含其他自定义Attribute的时候会报错

### ISSUE THREAD

**Issue by bishopjun11** [xljiulang/WebApiClient#6]
当接口返回对象定义了Protobuf 的Attribute的时候，但是我用Json反序列化的时候，就会报不能识别的Attribute的bug。
` [ProtoContract]
    public class AuthInfo
    {
        [ProtoMember(1)]
        public string AccessToken { get; set; }
    }`

**Comment by xljiulang** [comment]
把api接口定义和异常也提供一下

**Comment by bishopjun11** [comment]
代码我已经删除了，
Api接口定义类似如下：
` ITask<AuthInfo > UpdateUserWithFormAsync(UserInfo user);`
异常是说的意思不能识别的Attribute;
我觉得就是我定义的AuthInfo中包含了Protobuf的Attribute

**Comment by xljiulang** [comment]
此问题不是WebApiClient这层的问题：
1、如果服务端返回的是application/json，客户端在使用json.net进行json反序列化时，会无视[ProtoContract]这些和其它第三方特性；
2、如果服务端返回的是proto二进制数据，需要自己编写ApiReturnAttribute来处理这些数据的反序列化。

**Comment by xljiulang** [comment]
我也试了声明Protobuf特性的模型，从json反序列化来来没有问题
