### ISSUE TITLE
SetCookie() 存在Bug

### ISSUE THREAD

**Issue by CodeForCSharp** [xljiulang/WebApiClient#8]
```
return from item in cookieValues.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
       let kv = item.Split('=')
       let name = kv.FirstOrDefault().Trim()
       let value = kv.Length > 1 ? kv.LastOrDefault() : string.Empty
       let encode = HttpUtility.UrlEncode(value, encoding)
       select new Cookie(name, encode);
```
这里你用Split去处理，后面的Value也存在‘=’的话，你这里就会变成不止两段，而你却只获取最前和最后两段，是错误的。
另外这个地方我觉得不需要UrlEncode（这个你可以给我讲解一下为什么需要，谢谢）
我写了一段起码正确的代码如下：
```
       var list = new List<Cookie>();
       foreach (var item in Regex.Split(cookiesHeader, "; "))
       {
           var index = item.IndexOf('=');
           if (index < 0) continue;
           var name = item.Substring(0, index);
           var value = item.Substring(index + 1);
           list.Add(new Cookie(name, value));
       }
```
另外就是Cookie我觉得还有一个Bug，那就是序列化出来的CookieHeader居然用CookieContainer的SetCookie放进去只能得到一个值，简直让人无语。

**Comment by xljiulang** [comment]
Cookie只支持单字节字符，格式为{key}={value}，等号是关键字，如果{key}或{value}包含等号，应该在应用层处理。你的代码想处理等号，但没有考虑{key}包含等号的情况。

**Comment by CodeForCSharp** [comment]
确实如此，我是按照浏览器的默认行为来写的这一段代码，并且只是**大致上正确**，因为Cookie有很多特殊的情况我都没有处理。浏览器默认的行为是把第一个=号作为分隔符，所以虽然标准并没有规定Key不可以出现=，但是在实践上一般不会这么做。按照标准来说=号并不特别，cookie也没有什么关键字，特别的反而是空白，逗号和分号，这些才不允许在cookie里出现。
以上参考的标准是NetSpace发布的[](https://curl.haxx.se/rfc/cookie_spec.html)

**Comment by CodeForCSharp** [comment]
确实如此，我是按照浏览器的默认行为来写的这一段代码，并且只是大致上正确，因为Cookie有很多特殊的情况我都没有处理。浏览器默认的行为是把第一个=号作为分隔符，所以虽然标准并没有规定Key不可以出现=，但是在实践上一般不会这么做。按照标准来说=号并不特别，cookie也没有什么关键字，特别的反而是空白，逗号和分号，这些才不允许在cookie里出现。
以上参考的标准是NetSpace发布的[](https://curl.haxx.se/rfc/cookie_spec.html)

**Comment by CodeForCSharp** [comment]
我的代码是按照浏览器默认情况去写的，并且也只是保证了基本正确而已，因为Cookie有很多特殊情况我的代码并没有处理。浏览器的默认设置是把第一个=当作分割符，所以在实践上应该是不会有人在Name里面加入=的。就标准来说，并没有规定什么关键字，而且=号并不特别，反而是逗号，分号，空格是不允许出现的。
这里参考的标准是NetSpace发布的Spec [Spec](https://curl.haxx.se/rfc/cookie_spec.html)
当然后面有更为严格的标准出现，那就是RFC6265，它规定了Name只能包含**!#$%&'*+-.^_`|~**这些其他字符，Value只能包含**!#$%&'()*+-./:<=>?@[]^_`{|}~**这些其他字符。
这里参考的标准是[RFC 6265](http://www.ietf.org/rfc/rfc6265.txt) 第4.1.1节，里面引用的是[RFC 2616](https://tools.ietf.org/html/rfc)2616的2.2节。
所以我觉得这个代码应该是满足我自己描述的需求的。

**Comment by xljiulang** [comment]
增加了一个代码提交，类似PHP的SetCookie和SetRawCookie两个Api，HeaderAttribute增加EncodeCookie属性用于选择使用SetCookie或SetRawCookie，默认为true；两个Api都调用HttpUtility的IEnumerable<Cookie> ParseCookie(string cookieValues, bool useUrlEncode)方法。

**Comment by CodeForCSharp** [comment]
对了，我上面说这里还有很多特殊情况，我也一个个列出来，你看看你要不要去处理（这里指的是浏览器的一些行为，其实都是因为标准写的太烂，所以才那么多诡异的东西）。
1.Name或Value是空字符串应该也是可以被接受的。
2.不包含=的语句当作Name为空，比如value等价于=value。
3.控制字符不被允许。
4.允许出现空格和逗号之类的只要不是在value的前后就可以。
好像大概就这些吧，你可以考虑一下。

**Comment by xljiulang** [comment]
.net的Cookie类内部也做了验证处理，其实现为不支持空的name，value前后可以为空格。
